export const products = [
  {
    id: 1,
    title: "Gaming Mouse",
    category: "Mouse",
    price: 25,
    stock: 10,
    rating: 4.8,
    image: "/src/Gaming mouse.jpg",
  },
  {
    id: 2,
    title: "Mechanical Keyboard",
    category: "Keyboard",
    price: 60,
    stock: 5,
    rating: 4.7,
    image: "/src/RGB Backlit Mechanical Gaming Keyboard with Multimedia Control Knob.jpg",
  },
  {
    id: 3,
    title: "Gaming Headset",
    category: "Headset",
    price: 45,
    stock: 0,
    rating: 4.2,
    image: "/src/headset.jpg ",
  },
  {
    id: 4,
    title: "Monitor",
    category: "Monitor",
    price: 180,
    stock: 4,
    rating: 4.9,
    image: "/src/32 Inch QHD 180Hz Curved Gaming Monitor with 0_5ms & FreeSync.jpg",
  },
  {
    id: 5,
    title: "Chair",
    category: "Furniture",
    price: 150,
    stock: 2,
    rating: 4.6,
    image: "/src/Gaming & Streaming Chairs 2026 🎮 Ergonomic, Reclining & Long-Hour Comfort.jpg  ",
  },
  {
    id: 6,
    title: "Desk",
    category: "Furniture",
    price: 200,
    stock: 1,
    rating: 4.4,
    image: "/src/BestOffice Bureau de jeu.jpg",
  },
  {
    id: 7,
    title: "Webcam",
    category: "Accessory",
    price: 35,
    stock: 7,
    rating: 4.1,
    image: "./src/The Elgato Facecam 4K Supports Swappable Camera___.jpg",
  },
  {
    id: 8,
    title: "Microphone",
    category: "Accessory",
    price: 70,
    stock: 8,
    rating: 4.8,
    image: "./src/Fifine XLR_USB Dynamic Podcasting Microphone, Gaming Studio Computer PC Mic with RGB, Mute Button, Headphones Jack, Desktop Stand for Streaming.jpg",
  },
  {
    id: 9,
    title: "Controller",
    category: "Gaming",
    price: 55,
    stock: 0,
    rating: 4.5,
    image: "https://i.pinimg.com/736x/94/5f/31/945f317f3e3bc7afd59d4fb44a9628d7.jpg",
  },
  {
    id: 10,
    title: "SSD 1TB",
    category: "Storage",
    price: 90,
    stock: 9,
    rating: 4.9,
    image: "https://i.pinimg.com/1200x/9a/b6/66/9ab666f52808794b673173b89d94833b.jpg",
  },
  {
    id: 11,
    title: "RAM 16GB",
    category: "Memory",
    price: 80,
    stock: 3,
    rating: 4.7,
    image: "https://i.pinimg.com/736x/2a/a0/79/2aa079af5959d997dde7d15676b070ab.jpg",
  },
  {
    id: 12,
    title: "GPU",
    category: "Graphics",
    price: 450,
    stock: 2,
    rating: 5,
    image: "https://i.pinimg.com/1200x/d9/83/5c/d9835cc913940b865203d4cfe51d357d.jpg",
  },
];
