export const products = [
  {
    id: 1,
    title: "Gaming Mouse",
    category: "Mouse",
    price: 25,
    stock: 10,
    rating: 4.8,
    image: "https://via.placeholder.com/200?text=Mouse",
  },
  {
    id: 2,
    title: "Mechanical Keyboard",
    category: "Keyboard",
    price: 60,
    stock: 5,
    rating: 4.7,
    image: "https://via.placeholder.com/200?text=Keyboard",
  },
  {
    id: 3,
    title: "Gaming Headset",
    category: "Headset",
    price: 45,
    stock: 0,
    rating: 4.2,
    image: "https://via.placeholder.com/200?text=Headset",
  },
  {
    id: 4,
    title: "Monitor",
    category: "Monitor",
    price: 180,
    stock: 4,
    rating: 4.9,
    image: "https://via.placeholder.com/200?text=Monitor",
  },
  {
    id: 5,
    title: "Chair",
    category: "Furniture",
    price: 150,
    stock: 2,
    rating: 4.6,
    image: "https://via.placeholder.com/200?text=Chair",
  },
  {
    id: 6,
    title: "Desk",
    category: "Furniture",
    price: 200,
    stock: 1,
    rating: 4.4,
    image: "https://via.placeholder.com/200?text=Desk",
  },
  {
    id: 7,
    title: "Webcam",
    category: "Accessory",
    price: 35,
    stock: 7,
    rating: 4.1,
    image: "https://via.placeholder.com/200?text=Webcam",
  },
  {
    id: 8,
    title: "Microphone",
    category: "Accessory",
    price: 70,
    stock: 8,
    rating: 4.8,
    image: "https://via.placeholder.com/200?text=Mic",
  },
  {
    id: 9,
    title: "Controller",
    category: "Gaming",
    price: 55,
    stock: 0,
    rating: 4.5,
    image: "https://via.placeholder.com/200?text=Controller",
  },
  {
    id: 10,
    title: "SSD 1TB",
    category: "Storage",
    price: 90,
    stock: 9,
    rating: 4.9,
    image: "https://via.placeholder.com/200?text=SSD",
  },
  {
    id: 11,
    title: "RAM 16GB",
    category: "Memory",
    price: 80,
    stock: 3,
    rating: 4.7,
    image: "https://via.placeholder.com/200?text=RAM",
  },
  {
    id: 12,
    title: "GPU",
    category: "Graphics",
    price: 450,
    stock: 2,
    rating: 5,
    image: "https://via.placeholder.com/200?text=GPU",
  },
];
